name: Build and Deploy Patient-Microservice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        working-directory: ./patient-service
        run: mvn clean test

      - name: Build JAR
        working-directory: ./patient-service
        run: mvn clean package

      - name: Build and Push Docker Image
        working-directory: ./patient-service
        env:
          DOCKER_USER: simon123
          DOCKER_PASS: Shan2003+NR
        run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker build --no-cache -t simon/patient-microservice:latest .
          docker push simon/patient-microservice:latest
